x-common-env: &common-env
  SERVICE_HOST_ADDRESS: 10.0.4.40

services:

  main-app:
    image: coral-demo-app
    ports:
      - "8080:8080"
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: coral-main-app
      SERVICE_NAME: coral-main-app
      SIGNALFX_API_TOKEN: KyssNC-WFXmoB82mwYW1jw
      SPLUNK_ACCESS_TOKEN: KyssNC-WFXmoB82mwYW1jw
      SPLUNK_REALM: us1
      AGENT_TYPE: splunk
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev,service.version=1.0
      OTEL_EXPORTER_OTLP_ENDPOINT: https://ingest.us1.signalfx.com/v2/trace
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: https://ingest.us1.signalfx.com/v2/trace/otlp
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: https://ingest.us1.signalfx.com/v2/logs/otlp
    container_name: coral-main-app

  orders-service:
    image: coral-demo-app
    ports:
      - "8081:8080"
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: orders-service
      SERVICE_NAME: orders-service
      SIGNALFX_API_TOKEN: KyssNC-WFXmoB82mwYW1jw
      SPLUNK_ACCESS_TOKEN: KyssNC-WFXmoB82mwYW1jw
      SPLUNK_REALM: us1
      AGENT_TYPE: splunk
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev,service.version=1.0
      OTEL_EXPORTER_OTLP_ENDPOINT: https://ingest.us1.signalfx.com/v2/trace
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: https://ingest.us1.signalfx.com/v2/trace/otlp
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: https://ingest.us1.signalfx.com/v2/logs/otlp
    container_name: orders-service

  checkout-service:
    image: coral-demo-app
    ports:
      - "8082:8080"
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: checkout-service
      SERVICE_NAME: checkout-service
      SIGNALFX_API_TOKEN: KyssNC-WFXmoB82mwYW1jw
      SPLUNK_ACCESS_TOKEN: KyssNC-WFXmoB82mwYW1jw
      SPLUNK_REALM: us1
      AGENT_TYPE: splunk
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev,service.version=1.0
      OTEL_EXPORTER_OTLP_ENDPOINT: https://ingest.us1.signalfx.com/v2/trace
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: https://ingest.us1.signalfx.com/v2/trace/otlp
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: https://ingest.us1.signalfx.com/v2/logs/otlp
    container_name: checkout-service

  payment-service:
    image: coral-demo-app
    ports:
      - "8083:8080"
    environment:
      <<: *common-env
      AGENT_TYPE: appdynamics
      SERVICE_NAME: payment-service
    container_name: payment-service

