
micronaut:
  application:
    name: ${SERVICE_NAME:coral-demo-app}
  http:
    client:
      read-timeout: 30000 # milliseconds
      connect-timeout: 30000 # milliseconds
      max-content-length: 30971520  # 29.XXX MB
  metrics:
    enabled: true
    export:
      signalfx:
        enabled: true
        accessToken: ${SIGNALFX_API_TOKEN}
        step: PT1M
  server:
    port: ${SERVICE_PORT:8080}
otel:
  traces:
    exporter: logging,otlp
coral:
  endpoints:
    - name: health
      url: myhealth
      actions:
        - "request|http://localhost:8080/health"
        - "wait_random|1000"
    - name: info
      url: myinfo
      actions:
        - "request|http://localhost:8080/health"
        - "wait_random|1000"
